services:
  http-server-projeto-korp:
    build:
      context: ../../app
      dockerfile: ../infra/docker/Dockerfile
    image: http-server-projeto-korp:local
    expose:
      - "8080"
    env_file:
      - .env.local
    networks:
      - korp-project-network

  postgres:
    image: postgres:18.4-trixie
    env_file:
      - .env.local
    expose:
      - "5432"
    volumes:
      - korp-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 5s
    networks:
      - korp-project-network

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    env_file:
      - .env.local
    entrypoint: ["/bin/sh", "-c"]
    command: ["migrate -path=/migrations -database=postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@postgres:5432/$${POSTGRES_DB}?sslmode=disable up"]
    volumes:
      - ../../infra/postgres/migrations:/migrations:ro
    networks:
      - korp-project-network

  redis:
    image: redis:8.8.1-trixie
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 15
      start_period: 3s
    networks:
      - korp-project-network

  nginx:
    image: nginx:1.30.4
    ports:
      - "80:80"
    volumes:
      - ../../infra/nginx/http-server-projeto-korp.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - korp-project-network

  prometheus:
    image: prom/prometheus:v3.12.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    volumes:
      - ../../infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - korp-project-network

  grafana:
    image: grafana/grafana:13.0.4-ubuntu
    expose:
      - "3000"
    volumes:
      - ../../infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - korp-project-network

networks:
  korp-project-network:
    external: true

volumes:
  korp-postgres-data:
